# Generated by Django 4.2.9 on 2024-06-08 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num', models.CharField(help_text='Car factory number', max_length=255, unique=True)),
                ('engine_num', models.CharField(help_text='Engine factory number', max_length=255, unique=True)),
                ('transmission_num', models.CharField(help_text='Transmission factory number', max_length=255, unique=True)),
                ('main_bridge_num', models.CharField(help_text='Main bridge factory number', max_length=255, unique=True)),
                ('steerable_bridge_num', models.CharField(help_text='Steerable bridge factory number', max_length=255, unique=True)),
                ('supply_agreement', models.CharField(help_text='Supply agreement num, date', max_length=255)),
                ('factory_shipment_date', models.DateTimeField(help_text='Date of shipment from factory')),
                ('consignee', models.CharField(help_text='Shipment receiver', max_length=255, unique=True)),
                ('shipment_address', models.CharField(help_text='Address of shipment', max_length=255)),
                ('add_options', models.TextField(default='', help_text='Additional options')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Car model name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Car model description')),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Engine model name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Engine model description')),
            ],
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Failure node name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Failure node description')),
            ],
        ),
        migrations.CreateModel(
            name='MainBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Main bridge model name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Main bridge model description')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maintenance type name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Maintenance type description')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Recovery method name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Recovery method description')),
            ],
        ),
        migrations.CreateModel(
            name='SteerableBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Steerable bridge model name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Steerable bridge model description')),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Transmission model name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Transmission model description')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service company name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Service company description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateTimeField(help_text='Date of failure')),
                ('operating_time', models.FloatField(help_text='Operating time')),
                ('failure_description', models.TextField(default='', help_text='Failure description')),
                ('repair_parts', models.TextField(default='', help_text='Repair parts')),
                ('recovery_date', models.DateTimeField(help_text='Date of recovery')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.failurenode')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateTimeField(help_text='Date of shipment from factory')),
                ('operating_time', models.FloatField(help_text='Operating time')),
                ('work_order_num', models.CharField(help_text='Number of work order', max_length=255, unique=True)),
                ('work_order_date', models.CharField(help_text='Date of work order', max_length=255, unique=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicecompany')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maintenancetype')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.enginemodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='main_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainbridgemodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicecompany'),
        ),
        migrations.AddField(
            model_name='car',
            name='steerable_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.steerablebridgemodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transmissionmodel'),
        ),
    ]
