# Generated by Django 4.2.9 on 2024-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='qwerty', help_text='Client name', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
