# Generated by Django 4.2.9 on 2024-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_maintenance_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='consignee',
            field=models.CharField(help_text='Shipment receiver', max_length=255),
        ),
    ]
