# Generated by Django 4.2.9 on 2024-06-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_car_consignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_date',
            field=models.DateTimeField(help_text='Date of work order'),
        ),
    ]
