# Generated by Django 4.2.9 on 2024-06-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_maintenance_work_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='service_company',
        ),
    ]
